canal_tp_sam_homepage:
    pattern:  /
    defaults: { _controller: CanalTPSamCoreBundle:Sam:index }

sam_customer_list:
    pattern:  /customer
    defaults: { _controller: CanalTPSamCoreBundle:Customer:list }

sam_customer_new:
    pattern:  /customer/new
    defaults: { _controller: CanalTPSamCoreBundle:Customer:new }

sam_customer_edit:
    pattern:  /customer/{id}/edit
    defaults: { _controller: CanalTPSamCoreBundle:Customer:edit }

sam_customer_show:
    pattern:  /customer/{id}/show
    defaults: { _controller: CanalTPSamCoreBundle:Customer:show }

canal_tp_sam_network_list_json:
    pattern: /coverage/{externalCoverageId}/networks
    defaults: { _controller: CanalTPSamCoreBundle:Customer:byCoverage }
    options:
        expose: true

canal_tp_sam_network_check_permission_json:
    pattern: /coverage/{externalCoverageId}/networks/{externalNetworkId}/{token}
    defaults: { _controller: CanalTPSamCoreBundle:Customer:checkAllowedToNetwork }
    requirements:
        token: -?[a-zA-Z0-9_\-:]*
    options:
        expose: true

sam_customer_regeneratetoken:
    pattern:  /customer/{id}/token/{appId}/regenerate
    defaults: { _controller: CanalTPSamCoreBundle:Customer:regenerateToken }

sam_customer_regeneratealltokens:
    pattern:  /customer/{id}/tokens/regenerate
    defaults: { _controller: CanalTPSamCoreBundle:Customer:regenerateTokens }

sam_customer_listtokens:
    pattern:  /customer/{id}/tokens
    defaults: { _controller: CanalTPSamCoreBundle:Customer:listTokens }

#NMM
nmm_navitiaio_user:
    pattern:  /navitiaio/users
    defaults: { _controller: CanalTPNmmPortalBundle:NavitiaUser:list }

nmm_navitiaio_new:
    pattern:  /navitiaio/new
    defaults: { _controller: CanalTPNmmPortalBundle:NavitiaUser:new }

nmm_navitiaio_user_edit:
    pattern:  /navitiaio/users/{id}/edit
    defaults: { _controller: CanalTPNmmPortalBundle:NavitiaUser:edit }

nmm_navitiaio_user_listtokens:
    pattern:  /navitiaio/users/{id}/tokens
    defaults: { _controller: CanalTPNmmPortalBundle:NavitiaUser:listTokens }

nmm_navitiaio_user_regeneratetoken:
    pattern:  /navitiaio/users/{id}/tokens/regenerate
    defaults: { _controller: CanalTPNmmPortalBundle:NavitiaUser:regenerateToken }
