<?php

namespace CanalTP\NmmPortalBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CustomerApplicationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerApplicationRepository extends EntityRepository
{
    /**
     * Return active token to the couple customer/application
     *
     * @param type $customerId
     * @param type $applicationName
     * @return type
     */
    public function getActiveNavitiaToken($customerId, $applicationName)
    {
        $query = $this->getEntityManager()->createQueryBuilder()
            ->select('ca')
            ->from('CanalTPNmmPortalBundle:CustomerApplication', 'ca')
            ->join('ca.customer', 'c')
            ->join('ca.application', 'a')
            ->where('c.id = :customerId')
            ->andWhere('a.canonicalName = :appName')
            ->andWhere('ca.isActive = true')

            ->setParameters(array('customerId' => $customerId, 'appName' => $applicationName))
            ->getQuery();

        return $query->getOneOrNullResult();
    }
}
