<?php

namespace CanalTP\NmmPortalBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NavitiaEntityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NavitiaEntityRepository extends EntityRepository
{
    public function findNotCustomer()
    {
        $qb = $this->createQueryBuilder('n')
            ->leftJoin('CanalTP\NmmPortalBundle\Entity\Customer', 'c', 'WITH', 'c.navitiaEntity = n')
            ->where('c is null')
            ->orderBy('n.email');

        return $qb->getQuery()->getResult();
    }
}
