<?php

namespace CanalTP\NmmPortalBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NavitiaEntityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NavitiaTokenRepository extends EntityRepository
{
    public function disableToken($navEntity)
    {
        $queryText = 'UPDATE CanalTPNmmPortalBundle:NavitiaToken nt '
                . 'SET nt.isActive = false '
                . 'WHERE nt.navitiaEntity=:navEntity';

        $query = $this->_em->createQuery($queryText);
        $query->setParameter('navEntity', $navEntity);

        $query->execute();
    }
}
