<?php

namespace CanalTP\NmmPortalBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PerimeterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PerimeterRepository extends EntityRepository
{
    public function findPerimeterByCustomer($customer)
    {
        $query = $this->createQueryBuilder('p')
            ->join('p.navitiaEntity', 'ne')
            ->join('ne.customer', 'c')
            ->where('c.id = :customer')
            ->setParameter('customer', $customer)
            ->getQuery();

        return $query->getResult();
    }
}
